### ISSUE TITLE
Error trying to delete a reference with an empty source during upgrade to Plone 5

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.linkintegrity#32]
I'm running an upgrade from 4.0.10 to 5.0, via an intermediate 4.3.7 step.  While on 4.3.7 I migrate all content to plone.app.contenttypes before starting the 5.0 upgrade.

On 5.0, the upgrade fails with the following traceback:

```
2015-12-07 22:40:56 ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 257, in upgrade
    step['step'].doStep(setup)
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/Products.GenericSetup-1.8.0-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/plone.app.upgrade-1.3.18-py2.7.egg/plone/app/upgrade/v50/betas.py", line 353, in to50rc1
    migrate_linkintegrity_relations(portal)
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/plone.app.linkintegrity-3.0.2-py2.7.egg/plone/app/linkintegrity/upgrades.py", line 21, in migrate_linkintegrity_relations
    source_obj, target_obj, relationship=referencedRelationship)
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/Products.Archetypes-1.10.10-py2.7.egg/Products/Archetypes/ReferenceEngine.py", line 343, in deleteReference
    sID, sobj = self._uidFor(source)
  File "/Users/fulvio/Downloads/Plone-5.0/buildout-cache/eggs/Products.Archetypes-1.10.10-py2.7.egg/Products/Archetypes/ReferenceEngine.py", line 533, in _uidFor
    raise ReferenceException, "%r not referenceable" % uobject
ReferenceException: None not referenceable
```

In the `plone.app.linkintegrity.upgrades.migrate_linkintegrity_relations` call, `brain` has two non-empty values for `sourceUID` and `targetUID`, but `uuidToObject(brain.sourceUID)` produces `None`, while `uuidToObject(brain.targetUID)` is a jpg image object.
After that, `reference_catalog.deleteReference` is called with a `None` `source_obj`, and from there things go downhill.

I don't know why `brain.sourceUID` does not resolve to a valid object, and I don't know what should be done about it, but it seems that somewhere along the line there should be a safeguard against this case.

Also, if anyone has any suggestions on how to get around this so I can finish my upgrade, I would be much obliged.

**Comment by fulv** [comment]
Ok, I got around it by clearing the `reference_catalog` in Plone 4 before doing the upgrade.

**Comment by gforcada** [comment]
@fulv something to be added on the upgrade documentation?

**Comment by Martronic-SA** [comment]
I think clearing catalog is a workaround but not the solutions as ther are certainly references to keep.
You should just avoid migrating the ones that points to None with a try except / continue and migrating the good ones.
