### ISSUE TITLE
It raise ReferenceException: None not referenceable when upgrading from 4.3.11 to 5.0.6

### ISSUE THREAD

**Issue by b0n** [plone/plone.app.linkintegrity#48]
Same with issue #32 

```
(4308 → 4309)
Add Show Inactive criteria
(4309 → 4310)
Improve syndication
(4310 → 4311)
Miscellaneous
(4310 → 5000)
Run to50alpha1 upgrade profile
Use lowercase for email login
(4311 → 4312)
Unmark installed profiles that are no longer available.
Mark products as installed for installed uninstallable profiles
Cleanup uninstalled products
Cleanup the skins tool.
Remove fake kupu tool and related settings and resources.
(4312 → 4313)
Miscellaneous
(4313 → 4314)
Miscellaneous
(5000 → 5001)
Miscellaneous
(5001 → 5003)
Run to50alpha3 upgrade profile
Upgrade editing control panel settings
Upgrade maintenance control panel settings
Upgrade navigation control panel settings
Upgrade search control panel settings
Upgrade site control panel settings
(5003 → 5004)
Run to50beta1 upgrade profile
Upgrade markup control panel settings
Upgrade mail control panel settings
Upgrade security control panel settings
Remove Language Tool and migrate settings
(5004 → 5005)
Run to50beta2 upgrade profile
(5005 → 5006)
Run to50beta3 upgrade profile
(5006 → 5007)
Run to50beta4 upgrade profile
Run to50beta4 upgrade profile
(5007 → 5008)
Run to50rc1 upgrade profile
```

Error happened here

```
ERROR plone.app.upgrade Upgrade aborted. Error:
Traceback (most recent call last):
  File "/usr/local/Plone/buildout-cache/eggs/Products.CMFPlone-5.0.6-py2.7.egg/Products/CMFPlone/MigrationTool.py", line 268, in upgrade
    step['step'].doStep(setup)
  File "/usr/local/Plone/buildout-cache/eggs/Products.GenericSetup-1.8.3-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/usr/local/Plone/buildout-cache/eggs/plone.app.upgrade-1.3.27-py2.7.egg/plone/app/upgrade/v50/betas.py", line 353, in to50rc1
    migrate_linkintegrity_relations(portal)
  File "/usr/local/Plone/buildout-cache/eggs/plone.app.linkintegrity-3.0.6-py2.7.egg/plone/app/linkintegrity/upgrades.py", line 21, in migrate_linkintegrity_relations
    source_obj, target_obj, relationship=referencedRelationship)
  File "/usr/local/Plone/buildout-cache/eggs/Products.Archetypes-1.10.15-py2.7.egg/Products/Archetypes/ReferenceEngine.py", line 344, in deleteReference
    sID, sobj = self._uidFor(source)
  File "/usr/local/Plone/buildout-cache/eggs/Products.Archetypes-1.10.15-py2.7.egg/Products/Archetypes/ReferenceEngine.py", line 538, in _uidFor
    raise ReferenceException, "%r not referenceable" % uobject
ReferenceException: None not referenceable
INFO plone.app.upgrade End of upgrade path, main migration has finished.
ERROR plone.app.upgrade The upgrade path did NOT reach current version.
ERROR plone.app.upgrade Migration has failed
INFO plone.app.upgrade Dry run selected, transaction aborted
```

Rest of upgrading not work

```
(5008 → 5009)
Run to50rc2 upgrade profile
(5009 → 5010)
Run to50rc3 upgrade profile
Unmark installed profiles that are no longer available.
Mark products as installed for installed uninstallable profiles
Cleanup uninstalled products
(5010 → 5011)
Run to500 upgrade profile
(5011 → 5012)
Unmark installed profiles that are no longer available.
Mark products as installed for installed uninstallable profiles
Cleanup uninstalled products
Cleanup the skins tool.
Remove fake kupu tool and related settings and resources.
Run to501 upgrade profile.
(5012 → 5013)
Run to502 upgrade profile.
(5013 → 5014)
Run to503 upgrade profile.
(5014 → 5015)
Miscellaneous
(5015 → 5016)
Miscellaneous
```

**Comment by pbauer** [comment]
@b0n your reference-catalog seems to be inconsistent. You should rebuild it before migrating. The migration can only work when the data in your catalog is correct. As a quick fix you could also add a check to `plone.app.linkintegrity.upgrades.migrate_linkintegrity_relations` that skips when one on the brains in the catalog dos not exist in 'real life':

```python
if source_obj is None or target_obj is None: 
    continue
```

**Comment by b0n** [comment]
@pbauer It works fine. Thank you very much.

```python
def migrate_linkintegrity_relations(context):
    """Migrate linkintegrity-relation from reference_catalog to zc.relation"""
    reference_catalog = getToolByName(context, REFERENCE_CATALOG, None)
    if reference_catalog is not None:
        for brain in reference_catalog():
            # only handle linkintegrity-relations ('relatesTo')
            if brain.relationship != referencedRelationship:
                continue
            source_obj = uuidToObject(brain.sourceUID)
            target_obj = uuidToObject(brain.targetUID)
            if source_obj is None or target_obj is None:
                continue
            # Delete old reference
            reference_catalog.deleteReference(
                source_obj, target_obj, relationship=referencedRelationship)

            # Trigger the recreation of linkintegrity-relation in
            # the relation_catalog (zc.relation)
            modified(source_obj)
            modified(target_obj)
```

**Comment by pbauer** [comment]
My peasure.
